version: '3.8'

services:
  kubernetes-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: kubernetes-mcp-server
    container_name: k8s-mcp-server
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${KUBECONFIG:-/tmp/kubeconfig}:/kubeconfig:ro
    command:
      - --kubeconfig
      - /kubeconfig
      - --port
      - ${MCP_PORT:-8200}
      - --log-level
      - ${LOG_LEVEL:-1}
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-1}
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -q --spider http://localhost:${MCP_PORT:-8200}/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

